### ISSUE TITLE
Profile view for advocates

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/tenants#148]
- Profile view needs to display different items (org info, not address)
- Update profile view also needs to display different things

@atreni what does this look like from the main dashboard - icon on the header, link, etc?

**Comment by romeboards** [comment]
Sign out button(s)

**Comment by atreni** [comment]
This is a little different than the tenant app. Instead of saying "profile" at the top, just putting the actual name there. is it ok to switch this up?

![mobile advocate profile](https://cloud.githubusercontent.com/assets/7797826/22390137/516ce988-e4b7-11e6-820d-2aed24397088.jpg)
![advocate profile](https://cloud.githubusercontent.com/assets/7797826/22390139/52f510f0-e4b7-11e6-96df-f5e09f0affbf.jpg)

**Comment by atreni** [comment]
Mobile:
![update profile mobile](https://cloud.githubusercontent.com/assets/7797826/22629040/121a8004-ebad-11e6-85fd-89d735f6fc78.jpg)

Desktop:
![update profile](https://cloud.githubusercontent.com/assets/7797826/22629038/0a6875f0-ebad-11e6-9692-cbc6008c832d.jpg)

**Comment by atreni** [comment]
decided not to allow update advocate code for MVP. 
"Edit your advocate information" will house all the fields for updating their information, and change phone and password will only pertain to their log in information
